FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build frontend --configuration=production

FROM nginx:1.27-alpine
COPY --from=builder /app/dist/apps/frontend/browser /usr/share/nginx/html
COPY nginx.caprover.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
